pipeline {
    agent any
    
    options {
        skipStagesAfterUnstable()
    }
    
    stages {
        stage('Build') {
            steps {
                echo 'Building simple-python-pyinstaller-app...'
                sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing simple-python-pyinstaller-app...'
                sh 'python3 -m pytest sources/test_calc.py -v'
            }
        }
    }
}